title: niloofar-azizi
email: niloofar.azizi70@gmail.com
description: My awesome blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://niloofarazizi.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: niloofarazizi
github_username:  niloofar-azizi

paginate: 6
paginate_path: "/page:num/"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
